name: Build kernel on PR

on:
  workflow_dispatch:

jobs:
  Build:
    name: Compile and upload kernel
    runs-on: rockchip
    if: ${{ github.repository_owner == 'armbian' }}
    env:
      OCI_TARGET_BASE: "ghcr.io/${{ github.repository }}/"
      COMMIT_SHA: ${{ github.event.inputs.commit_sha }}
    steps:
      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout build repo
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          ref: main
          fetch-depth: 1
          clean: false

      - name: Build arm64 kernel at ${{ env.COMMIT_SHA }}
        id: kernel-arm64
        run: |
          rm -rf output/debs/*
          mkdir -p userpatches/extensions/
          cat <<- EOF > userpatches/extensions/pull-request.sh
          function post_family_config__force_commit_for_rk3588() {
              KERNELBRANCH="commit:${{ env.COMMIT_SHA }}"
          }
          EOF
          bash ./compile.sh kernel \
          SHARE_LOG=yes \
          BOARD=orangepi5 \
          BRANCH=vendor \
          ENABLE_EXTENSIONS="pull-request"

      - name: Build armhf kernel at ${{ env.COMMIT_SHA }}
        id: kernel-armhf
        run: |
          mkdir -p userpatches/extensions/
          cat <<- EOF > userpatches/extensions/pull-request.sh
          function post_family_config__force_commit_for_rk3588() {
              KERNELBRANCH="commit:${{ env.COMMIT_SHA }}"
          }
          EOF
          bash ./compile.sh kernel \
          SHARE_LOG=yes \
          BOARD=armsom-forge1 \
          BRANCH=vendor \
          ENABLE_EXTENSIONS="pull-request"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-rockchip-vendor
          path: output/debs/*.deb
          retention-days: 5
